/**
 * letsrolld API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import ArrayOfDirectors from './model/ArrayOfDirectors';
import ArrayOfFilms from './model/ArrayOfFilms';
import ArrayOfReports from './model/ArrayOfReports';
import Director from './model/Director';
import DirectorFilmsInner from './model/DirectorFilmsInner';
import DirectorFilmsInnerCountriesInner from './model/DirectorFilmsInnerCountriesInner';
import DirectorFilmsInnerOffersInner from './model/DirectorFilmsInnerOffersInner';
import DirectorInfo from './model/DirectorInfo';
import Film from './model/Film';
import Report from './model/Report';
import ReportSectionsInner from './model/ReportSectionsInner';
import DefaultApi from './api/DefaultApi';


/**
* JS API client generated by OpenAPI Generator.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var LetsrolldApi = require('index'); // See note below*.
* var xxxSvc = new LetsrolldApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new LetsrolldApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new LetsrolldApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new LetsrolldApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 0.1
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The ArrayOfDirectors model constructor.
     * @property {module:model/ArrayOfDirectors}
     */
    ArrayOfDirectors,

    /**
     * The ArrayOfFilms model constructor.
     * @property {module:model/ArrayOfFilms}
     */
    ArrayOfFilms,

    /**
     * The ArrayOfReports model constructor.
     * @property {module:model/ArrayOfReports}
     */
    ArrayOfReports,

    /**
     * The Director model constructor.
     * @property {module:model/Director}
     */
    Director,

    /**
     * The DirectorFilmsInner model constructor.
     * @property {module:model/DirectorFilmsInner}
     */
    DirectorFilmsInner,

    /**
     * The DirectorFilmsInnerCountriesInner model constructor.
     * @property {module:model/DirectorFilmsInnerCountriesInner}
     */
    DirectorFilmsInnerCountriesInner,

    /**
     * The DirectorFilmsInnerOffersInner model constructor.
     * @property {module:model/DirectorFilmsInnerOffersInner}
     */
    DirectorFilmsInnerOffersInner,

    /**
     * The DirectorInfo model constructor.
     * @property {module:model/DirectorInfo}
     */
    DirectorInfo,

    /**
     * The Film model constructor.
     * @property {module:model/Film}
     */
    Film,

    /**
     * The Report model constructor.
     * @property {module:model/Report}
     */
    Report,

    /**
     * The ReportSectionsInner model constructor.
     * @property {module:model/ReportSectionsInner}
     */
    ReportSectionsInner,

    /**
    * The DefaultApi service constructor.
    * @property {module:api/DefaultApi}
    */
    DefaultApi
};
