/**
 * letsrolld API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { DirectorFilmsInnerCountriesInner } from './directorFilmsInnerCountriesInner';
import { DirectorFilmsInnerOffersInner } from './directorFilmsInnerOffersInner';
import { DirectorInfo } from './directorInfo';

export class Film {
    'id'?: number;
    'title': string;
    'description'?: string;
    'year'?: number | null;
    'rating'?: string;
    'runtime'?: number | null;
    'lbUrl'?: string;
    'jwUrl'?: string | null;
    'trailerUrl'?: string | null;
    'genres'?: Array<string>;
    'countries'?: Array<DirectorFilmsInnerCountriesInner>;
    'offers'?: Array<DirectorFilmsInnerOffersInner>;
    'directors'?: Array<DirectorInfo>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "year",
            "baseName": "year",
            "type": "number"
        },
        {
            "name": "rating",
            "baseName": "rating",
            "type": "string"
        },
        {
            "name": "runtime",
            "baseName": "runtime",
            "type": "number"
        },
        {
            "name": "lbUrl",
            "baseName": "lb_url",
            "type": "string"
        },
        {
            "name": "jwUrl",
            "baseName": "jw_url",
            "type": "string"
        },
        {
            "name": "trailerUrl",
            "baseName": "trailer_url",
            "type": "string"
        },
        {
            "name": "genres",
            "baseName": "genres",
            "type": "Array<string>"
        },
        {
            "name": "countries",
            "baseName": "countries",
            "type": "Array<DirectorFilmsInnerCountriesInner>"
        },
        {
            "name": "offers",
            "baseName": "offers",
            "type": "Array<DirectorFilmsInnerOffersInner>"
        },
        {
            "name": "directors",
            "baseName": "directors",
            "type": "Array<DirectorInfo>"
        }    ];

    static getAttributeTypeMap() {
        return Film.attributeTypeMap;
    }
}

