/**
 * letsrolld API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ReportSectionsInner } from './reportSectionsInner';

export class Report {
    'id': number;
    'name': string;
    'sections'?: Array<ReportSectionsInner>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "sections",
            "baseName": "sections",
            "type": "Array<ReportSectionsInner>"
        }    ];

    static getAttributeTypeMap() {
        return Report.attributeTypeMap;
    }
}

