/**
 * letsrolld API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ArrayOfReports model module.
 * @module model/ArrayOfReports
 * @version 0.1
 */
class ArrayOfReports extends Array {
    /**
     * Constructs a new <code>ArrayOfReports</code>.
     * @alias module:model/ArrayOfReports
     * @extends Array
     */
    constructor() { 
        super();
        
        
        ArrayOfReports.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ArrayOfReports</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ArrayOfReports} obj Optional instance to populate.
     * @return {module:model/ArrayOfReports} The populated <code>ArrayOfReports</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ArrayOfReports();

            ApiClient.constructFromObject(data, obj, 'Object');
            

        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ArrayOfReports</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ArrayOfReports</code>.
     */
    static validateJSON(data) {

        return true;
    }


}








export default ArrayOfReports;

