/**
 * letsrolld API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The DirectorFilmsInnerCountriesInner model module.
 * @module model/DirectorFilmsInnerCountriesInner
 * @version 0.1
 */
class DirectorFilmsInnerCountriesInner {
    /**
     * Constructs a new <code>DirectorFilmsInnerCountriesInner</code>.
     * @alias module:model/DirectorFilmsInnerCountriesInner
     * @param name {String} 
     */
    constructor(name) { 
        
        DirectorFilmsInnerCountriesInner.initialize(this, name);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name) { 
        obj['name'] = name;
    }

    /**
     * Constructs a <code>DirectorFilmsInnerCountriesInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DirectorFilmsInnerCountriesInner} obj Optional instance to populate.
     * @return {module:model/DirectorFilmsInnerCountriesInner} The populated <code>DirectorFilmsInnerCountriesInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DirectorFilmsInnerCountriesInner();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('flag')) {
                obj['flag'] = ApiClient.convertToType(data['flag'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>DirectorFilmsInnerCountriesInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>DirectorFilmsInnerCountriesInner</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of DirectorFilmsInnerCountriesInner.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['flag'] && !(typeof data['flag'] === 'string' || data['flag'] instanceof String)) {
            throw new Error("Expected the field `flag` to be a primitive type in the JSON string but got " + data['flag']);
        }

        return true;
    }


}

DirectorFilmsInnerCountriesInner.RequiredProperties = ["name"];

/**
 * @member {String} name
 */
DirectorFilmsInnerCountriesInner.prototype['name'] = undefined;

/**
 * @member {String} flag
 */
DirectorFilmsInnerCountriesInner.prototype['flag'] = undefined;






export default DirectorFilmsInnerCountriesInner;

