/**
 * letsrolld API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import DirectorFilmsInner from './DirectorFilmsInner';

/**
 * The ReportSectionsInner model module.
 * @module model/ReportSectionsInner
 * @version 0.1
 */
class ReportSectionsInner {
    /**
     * Constructs a new <code>ReportSectionsInner</code>.
     * @alias module:model/ReportSectionsInner
     * @param name {String} 
     * @param films {Array.<module:model/DirectorFilmsInner>} 
     */
    constructor(name, films) { 
        
        ReportSectionsInner.initialize(this, name, films);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name, films) { 
        obj['name'] = name;
        obj['films'] = films;
    }

    /**
     * Constructs a <code>ReportSectionsInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ReportSectionsInner} obj Optional instance to populate.
     * @return {module:model/ReportSectionsInner} The populated <code>ReportSectionsInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ReportSectionsInner();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('films')) {
                obj['films'] = ApiClient.convertToType(data['films'], [DirectorFilmsInner]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ReportSectionsInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ReportSectionsInner</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ReportSectionsInner.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        if (data['films']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['films'])) {
                throw new Error("Expected the field `films` to be an array in the JSON data but got " + data['films']);
            }
            // validate the optional field `films` (array)
            for (const item of data['films']) {
                DirectorFilmsInner.validateJSON(item);
            };
        }

        return true;
    }


}

ReportSectionsInner.RequiredProperties = ["name", "films"];

/**
 * @member {String} name
 */
ReportSectionsInner.prototype['name'] = undefined;

/**
 * @member {Array.<module:model/DirectorFilmsInner>} films
 */
ReportSectionsInner.prototype['films'] = undefined;






export default ReportSectionsInner;

