name: pre-commit
on: [pull_request]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
    - name: Install distro dependencies
      run: |
        sudo apt-get update
        sudo apt-get install shellcheck
    - uses: pre-commit/action@v3.0.1
