name: Swagger
on: [pull_request]
jobs:
  swagger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.x'

      - name: Install nodejs
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install java
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Install make
        run: |
          sudo apt-get update
          sudo apt-get install make

      - name: Install pdm
        run: |
          python -m pip install --upgrade pip
          pip install pdm

      - name: Install the package
        run: |
          pdm install

      - name: Re-generate swagger.json
        run: |
          diff -u swagger.json <(pdm run swagger)

      - name: Install openapi-generator-cli
        run: |
          npm install @openapitools/openapi-generator-cli -g

      - name: Validate swagger.json
        run: |
          openapi-generator-cli validate -i swagger.json

      - name: Re-generate client bindings
        run: |
          make swagger-all
